### ISSUE TITLE
Does not open with strict HTTPS policies

### ISSUE THREAD

**Issue by sobolevn** [gayanvoice/githubstats#4]
Hi, I have tried to access your website with Brave Browser, which enforces strict HTTPS policies.
And it does not work for users with this feature on.

That's what it says: `ERR_SSL_PROTOCOL_ERROR`

**Comment by gayanvoice** [comment]
https gives some protection over personal data. since this app does not require any sort of login or user inputs you can use it without having a https connection on google chrome or firefox. i will configure it with a ssl certificate.

**Comment by gayanvoice** [comment]
You can use HTTP http://www.githubstats.com and HTTPS on https://githubstats-com.herokuapp.com/
