### ISSUE TITLE
Page has bug and not working

### ISSUE THREAD

**Issue by igorjos** [gayanvoice/githubstats#7]
Steps to replicate, 

1. open the page (and inspect element)
2. select country
3. click on any range
Error:
SyntaxError: Unexpected token < in JSON at position 0
console.<computed> @ index.js:1375

As I can log the server returns 500 because file not found (Macedonia, Serbia JSON)

**Comment by gayanvoice** [comment]
Yeap there is an update is going on. Just wait for few hours.
